<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_cargue_de_material_a_tecnicos_contratistas  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		$data = array();
$data["Material"] = $values["Material"];
$data["Cantidad"] = $values["Cantidad"]*(-1);
$data["Tecnico"] = $values["Bodega"];
$data["Empresa"] = $values["Empresa"];
DB::Insert("inventario_ general", $data )

and

$data = array();
$data["Material"] = $values["Material"];
$data["Cantidad"] = $values["Cantidad"];
$data["Tecnico"] = $values["Tecnico"];
$data["Empresa"] = $values["Empresa"];
DB::Insert("inventario_ general", $data )

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>