<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_material_recuperado  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$data = array();
$data["Material"] = $values["Material"];
$data["Cantidad"] = $values["Cantidad"];
$data["Tecnico"] = $values["Tecnico"];
$data["Empresa"] = $values["Empresa"];
$data["Fecha"] = $values["Fecha de Consumo"];
$data["Ticket"] = $values["Ticket"];
$data["Id Ingreso"] = $values["Id Ingreso"];
DB::Insert("inventario_ general", $data )
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>